site_name: YHKLAB Wiki

theme:
    name: 'material'
    features:
        - navigation.tabs
        - navigation.instant
        - navigation.sections
        - navigation.top

plugins:
        - search
        - mermaid2
        - glightbox
        - git-revision-date-localized:
                enable_parallel_processing: false

extra_javascript:
  - javascripts/config.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - attr_list
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - pymdownx.arithmatex:
        generic: true
validation:
    links:
        not_found: ignore
        absolute_links: ignore
nav:
        - Home: index.md
        - 시작하기:
                - 1. 원격 개발 환경 구축:
                        - A. 연구실 클러스터 (HPC) : getting-started/lab-cluster.md
                        - B. 로컬 Python (Anaconda) : getting-started/python-setup.md
                        - C. WSL : getting-started/wsl.md
                - 2. 버전관리:
                        - A. Git 저장소 시작하기 : getting-started/git-create-repository.md
                - 3. 명령어 cheat sheet:
                        - A. Python : cheatsheets/python.md
                        - B. Linux : cheatsheets/linux.md
                        - C. Anaconda : cheatsheets/anaconda.md
                        - D. Emacs : cheatsheets/emacs.md
                        - E. MkDocs : cheatsheets/mkdocs.md
        - 교육용:
                - Atomic unit: education/atomic-unit-dimension-analysis.md
        - Atom:
                - 1. 설치: installation/atom.md
                - 2. ATOM 계산:
                        - A. 기초 과정:
                                - '(1) 모든-전자 계산' : atom/all-electron.md
                                - '(2) 슈도퍼텐셜 생성' : atom/pseudopotential.md
        - SIESTA:
                - 0. 준비:
                        - A. SIESTA 클러스터에서 설치 : installation/siesta-cluster.md
                        - B. SIESTA Edison에서 설치 : installation/siesta-edison.md
                        - C. SIESTA 로컬에서 설치 : installation/siesta-local.md
                - 1. SIESTA 계산:
                        - A. 기초 과정:
                                - (1) SIESTA 개요 : siesta/basic.md
                                - (2) 분자 계산 실습 (CH4, H2O, NH3) : siesta/ch4-h20-nh3.md
                                - (3) 3D - Au bulk 구조 : siesta/gold-bulk.md
                                - (4-1) 2D - Au slab 구조: siesta/gold-slab.md
                                - (4-2) 2D - Graphene : siesta/graphene.md
                - 2. TranSIESTA 계산:
                        - A. 기초 과정:
                                - (1) TranSIESTA 개요 : transiesta/overview.md
                                - (2) 접합구조 모델링 : transiesta/junction-modeling.md
                                - (3) Si chain (1D) : transiesta/si-chain-1d.md
                        - B. 중급/고급 과정:
                                - (1) 평형상태 계산:
                                        - 1) 그래핀 (2D) : transiesta/graphene.md
                                        - 2) 깨끗한 or 결함있는 GNRs: transiesta/gnr.md
                                        - 3) Si-SiO2-Si : transiesta/si-sio2-si.md
                                - (2) 비평형상태 계산:
                                        - 1) GNRs-진공-GNRs : transiesta/gnr-vacuum-gnr.md
        - VASP:
                - Nudged Elastic Band (NEB):
                        - Machine learning for nudged elastic band : vasp/machine-learning-neb.md
        - OORINano:
                - 1. k-point sampling : nanocore/k-point-sampling.md
                - 2. Structure optimization :
                        - A. Equation of state (EOS) : nanocore/equation-of-state.md
                        - B. Murnaghan fitting : nanocore/murnaghan-fitting.md
                        - C. Geometry optimization : nanocore/geometry-optimization.md
        - About: about.md
